Oauth support
frenck/python-tailscale pull request #379
Opened 2023-07-20 05:44 UTC by clayrosenthal

# Proposed Changes

Adding support for oauth client authentication. See [Tailscale docs](https://tailscale.com/kb/1215/oauth-clients/)

2023-07-20 05:52 UTC, frenck requested changes
Please don't make changes that are not related to the core/goal
Of the pr.

This is the same review comment as the previous PR.

2023-07-20 05:52 UTC, frenck commented on .pre-commit-config.yaml
> +        entry: npm run pyright --venvpath $(poetry env info -p)
Unrelated change

2023-07-20 05:52 UTC, frenck commented on README.md
> +[contribution guidelines](.github/CONTRIBUTING.md).
Unrelated change

2023-07-20 05:52 UTC, frenck commented on package.json
> +  "version": "0.4.0",
This should not be changed

2023-07-20 05:52 UTC, frenck commented on pyproject.toml
> +authors = ["Franck Nijhof <opensource@frenck.dev>", "Clay Rosenthal <clayrosenthal@gmail.com>"]
This is not for contributors, please revert

2023-07-20 05:52 UTC, frenck commented on pyproject.toml
> +[tool.pyright]
Unrelated change

2023-07-20 05:52 UTC, frenck commented on src/tailscale/models.py
> +    node_id: str = Field(..., alias="nodeId")
Unrelated change

2023-07-20 05:52 UTC, frenck commented on src/tailscale/models.py
> +    client_connectivity: Optional[ClientConnectivity] = Field(
Unrelated change

2023-07-20 05:52 UTC, frenck commented on src/tailscale/tailscale.py
> +    async def devices(self, all_fields: bool = True) -> Dict[str, Device]:
Unrelated change

2023-07-20 05:52 UTC, frenck commented on src/tailscale/tailscale.py
> +    async def device(self, device_id: str, all_fields: bool = True) -> Device:
Unrelated change

2023-07-20 06:49 UTC, clayrosenthal commented
I did the first round from memory, thanks for clarifying the extras. Tried my best to cleanup the commit history, but I still think you would want to squash it

2023-07-31 18:47 UTC, clayrosenthal commented
hey @frenck, do you have any other feedback or revisions you'd like me to make? Is it still too large?

2023-09-08 08:02 UTC, closed without merging